# Generated by Django 2.2.7 on 2020-01-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('races', '0009_auto_20200115_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Races',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=120)),
                ('time_date', models.DateTimeField()),
                ('start', models.CharField(max_length=120)),
                ('finish', models.CharField(max_length=120)),
                ('distance', models.FloatField(max_length=50)),
                ('base_stake', models.FloatField()),
                ('jackpot', models.FloatField()),
                ('winner', models.CharField(max_length=120)),
                ('drivers', models.IntegerField()),
                ('stakes', models.IntegerField()),
                ('race_past', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=5)),
            ],
        ),
    ]
