# Generated by Django 2.2.7 on 2020-01-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0010_races'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Races',
            new_name='Race',
        ),
    ]
