# Generated by Django 2.2.7 on 2020-01-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0011_auto_20200115_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_past',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='race',
            name='winner',
            field=models.CharField(choices=[('Marko', 'Marko Karpats')], max_length=120),
        ),
    ]
