# Generated by Django 2.2.7 on 2020-01-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0012_auto_20200115_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='driver_list',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='race',
            name='base_stake',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='race',
            name='drivers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='race',
            name='jackpot',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='race',
            name='stakes',
            field=models.IntegerField(default=0),
        ),
    ]
