# Generated by Django 2.2.7 on 2020-01-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0013_auto_20200115_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='allowed_cars',
            field=models.CharField(default='no limits', max_length=100),
        ),
    ]
