# Generated by Django 3.0 on 2020-01-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0014_race_allowed_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='driver_list',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='winner',
            field=models.CharField(choices=[('None', 'None'), ('Marko', 'Marko Karpats')], max_length=120),
        ),
    ]
