# Generated by Django 3.0 on 2020-01-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0015_auto_20200115_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='winner',
            field=models.CharField(choices=[('None', 'None'), ('Marko', 'Marko Karpats')], default='None', max_length=120),
        ),
    ]
