# Generated by Django 2.2.7 on 2020-01-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0017_auto_20200116_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='driver_list',
            field=models.TextField(default='|'),
        ),
        migrations.AlterField(
            model_name='race',
            name='winner',
            field=models.CharField(choices=[('None', 'None'), ('Admin', 'Admin BOS'), ('Marko', 'Marko Karpats')], default='None', max_length=120),
        ),
    ]
