# Generated by Django 2.2.7 on 2020-01-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0018_auto_20200119_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='winner',
            field=models.CharField(choices=[('None', 'None'), ('Admin BOS', 'Admin BOS'), ('Marko Karpats', 'Marko Karpats')], default='None', max_length=120),
        ),
    ]
