# Generated by Django 2.2.7 on 2020-01-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0019_auto_20200120_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_past',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5),
        ),
        migrations.AlterField(
            model_name='race',
            name='winner',
            field=models.CharField(choices=[('None', 'None'), ('Marko Karpats', 'Marko Karpats')], default='None', max_length=120),
        ),
    ]
