# Generated by Django 2.2.7 on 2020-01-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0020_auto_20200121_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='time_before_race',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
