# Generated by Django 2.2.7 on 2020-01-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0023_auto_20200122_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='winner',
            field=models.CharField(choices=[('None', 'None')], default='None', max_length=120),
        ),
    ]
