# Generated by Django 2.2.7 on 2020-01-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0024_auto_20200122_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='winner',
            field=models.CharField(choices=[('None', 'None'), ('Алексей Тимонин', 'Алексей Тимонин'), ('Дима Михалевич', 'Дима Михалевич'), ('Илья Удре', 'Илья Удре'), ('Марко Карпац', 'Марко Карпац')], default='None', max_length=120),
        ),
    ]
