# Generated by Django 3.0 on 2020-02-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0025_auto_20200122_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='entery_price',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='race',
            name='opened',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Opened', 'Opened')], default='Closed', max_length=10),
        ),
    ]
