# Generated by Django 2.2.7 on 2020-01-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_auto_20191211_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakes',
            name='name',
            field=models.CharField(choices=[('Marko', 'Marko Karpats')], max_length=50),
        ),
    ]
