# Generated by Django 2.2.7 on 2020-01-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0004_auto_20200115_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakes',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
