# Generated by Django 2.2.7 on 2020-01-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0005_auto_20200115_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakes',
            name='name',
            field=models.CharField(choices=[('Marko', 'Marko Karpats')], max_length=50),
        ),
    ]
