# Generated by Django 2.2.7 on 2020-01-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0006_auto_20200115_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakes',
            name='name',
            field=models.CharField(choices=[('Admin', 'Admin BOS'), ('Marko', 'Marko Karpats')], max_length=50),
        ),
    ]
