# Generated by Django 2.2.7 on 2020-01-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0007_auto_20200119_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakes',
            name='expected_winner_name',
        ),
        migrations.RemoveField(
            model_name='stakes',
            name='expected_winner_surname',
        ),
        migrations.AddField(
            model_name='stakes',
            name='winner_name',
            field=models.CharField(choices=[('Admin', 'Admin BOS'), ('Marko', 'Marko Karpats')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
