# Generated by Django 2.2.7 on 2020-01-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0008_auto_20200120_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakes',
            name='paymnet_method',
            field=models.CharField(choices=[('card', 'card'), ('cash', 'cash')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
