# Generated by Django 2.2.7 on 2020-01-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0009_stakes_paymnet_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakes',
            name='race_name',
            field=models.CharField(choices=[('Grand Opening:First Race', 'Grand Opening:First Race'), ('Test', 'Test')], default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stakes',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10),
        ),
    ]
