# Generated by Django 2.2.7 on 2020-01-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0010_auto_20200120_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakes',
            name='coeficient',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
