# Generated by Django 2.2.7 on 2020-01-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0011_stakes_coeficient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stakes',
            new_name='Stake',
        ),
    ]
