# Generated by Django 2.2.7 on 2020-01-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0014_auto_20200120_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='stake',
            name='bank_account_number',
            field=models.CharField(default='EE302200221043383149', max_length=300),
        ),
        migrations.AddField(
            model_name='stake',
            name='bet_code',
            field=models.CharField(default='Bzz! #0000', max_length=300),
        ),
    ]
