# Generated by Django 2.2.7 on 2020-01-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0015_auto_20200120_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stake',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stake',
            name='winner_name',
            field=models.CharField(max_length=50),
        ),
    ]
