# Generated by Django 2.2.7 on 2020-01-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0016_auto_20200120_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stake',
            name='name',
            field=models.CharField(choices=[('Admin BOS', 'Admin BOS'), ('Marko Karpats', 'Marko Karpats')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stake',
            name='winner_name',
            field=models.CharField(choices=[('Marko Karpats', 'Marko Karpats')], max_length=50),
        ),
    ]
