# Generated by Django 2.2.7 on 2020-01-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0017_auto_20200121_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stake',
            name='name',
            field=models.CharField(choices=[('Admin BOS', 'Admin BOS'), ('Марко Карпац', 'Марко Карпац'), ('Алексей Тимонин', 'Алексей Тимонин'), ('Дима Михалевич', 'Дима Михалевич'), ('Илья Удре', 'Илья Удре')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stake',
            name='winner_name',
            field=models.CharField(choices=[('Алексей Тимонин', 'Алексей Тимонин'), ('Дима Михалевич', 'Дима Михалевич'), ('Илья Удре', 'Илья Удре'), ('Марко Карпац', 'Марко Карпац')], max_length=50),
        ),
    ]
