# Generated by Django 2.2.7 on 2020-01-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0018_auto_20200122_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stake',
            name='race_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stake',
            name='winner_name',
            field=models.CharField(max_length=50),
        ),
    ]
