# Generated by Django 2.2.7 on 2020-01-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0019_auto_20200122_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stake',
            name='race_name',
            field=models.CharField(choices=[('Grand Opening:First Race', 'Grand Opening:First Race'), ('Test', 'Test')], max_length=200),
        ),
        migrations.AlterField(
            model_name='stake',
            name='winner_name',
            field=models.CharField(choices=[('Алексей Тимонин', 'Алексей Тимонин'), ('Дима Михалевич', 'Дима Михалевич'), ('Илья Удре', 'Илья Удре'), ('Марко Карпац', 'Марко Карпац')], max_length=50),
        ),
    ]
