# Generated by Django 2.2.7 on 2020-01-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0020_auto_20200122_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='stake',
            name='won',
            field=models.CharField(choices=[('None', 'None'), ('Won', 'Won'), ('Lost', 'Lost')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='stake',
            name='name',
            field=models.CharField(choices=[('Admin BOS', 'Admin BOS'), ('Алексей Тимонин', 'Алексей Тимонин'), ('Дима Михалевич', 'Дима Михалевич'), ('Илья Удре', 'Илья Удре'), ('Марко Карпац', 'Марко Карпац')], max_length=50),
        ),
    ]
