# Generated by Django 3.0 on 2020-02-04 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0023_stake_opened'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stake',
            name='opened',
        ),
    ]
