# Generated by Django 3.0 on 2020-02-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0024_remove_stake_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='stake',
            name='jackpot',
            field=models.FloatField(default=0),
        ),
    ]
