# Generated by Django 2.2.7 on 2020-02-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0025_stake_jackpot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stake',
            name='name',
            field=models.CharField(choices=[('Admin BOS', 'Admin BOS'), ('Алексей Тимонин', 'Алексей Тимонин'), ('Дима Михалевич', 'Дима Михалевич'), ('Илья Удре', 'Илья Удре'), ('Марко Карпац', 'Марко Карпац'), ('Николай Огоньков', 'Николай Огоньков'), ('Даниель Гасинский', 'Даниель Гасинский'), ('Артур Алипьев', 'Артур Алипьев')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stake',
            name='status_won',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10),
        ),
        migrations.AlterField(
            model_name='stake',
            name='won',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Won', 'Won'), ('Lost', 'Lost')], default='None', max_length=10),
        ),
    ]
