# Generated by Django 3.0 on 2020-01-14 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_auto_20191209_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='date_of_getting_driving_licens',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
