# Generated by Django 2.2.7 on 2020-01-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_auto_20200114_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivers',
            name='date_of_getting_driving_licens',
        ),
    ]
