# Generated by Django 2.2.7 on 2020-01-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_remove_drivers_date_of_getting_driving_licens'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='login',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
