# Generated by Django 2.2.7 on 2020-01-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_drivers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drivers',
        ),
    ]
