# Generated by Django 2.2.7 on 2020-01-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0011_drivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='login',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drivers',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10),
        ),
    ]
