# Generated by Django 2.2.7 on 2020-01-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0013_drivers_reg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='coeficient',
            field=models.FloatField(default=0),
        ),
    ]
