# Generated by Django 3.0 on 2020-01-14 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0015_auto_20191211_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_profile',
            name='date_of_getting_driving_licens',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='account_profile',
            name='races_participated',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account_profile',
            name='races_won',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account_profile',
            name='account_create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
