# Generated by Django 3.0 on 2020-01-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0016_auto_20200114_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_profile',
            name='races_participated',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account_profile',
            name='races_won',
            field=models.IntegerField(default=0),
        ),
    ]
