# Generated by Django 2.2.7 on 2020-01-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0018_account_profile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_profile',
            name='email',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
