# Generated by Django 2.2.7 on 2020-01-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0020_remove_account_profile_date_of_getting_driving_licens'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_profile',
            name='driving_licens',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default=False, max_length=5),
        ),
    ]
