# Generated by Django 2.2.7 on 2020-01-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0021_account_profile_driving_licens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_profile',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
