# Generated by Django 2.2.7 on 2020-01-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0023_auto_20200115_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_profile',
            name='login',
        ),
    ]
