# Generated by Django 3.0 on 2020-01-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0025_account_profile_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_profile',
            name='races_registered',
            field=models.TextField(blank=True),
        ),
    ]
