# Generated by Django 2.2.7 on 2020-01-16 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0026_account_profile_races_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_profile',
            name='races_registered',
        ),
    ]
