# Generated by Django 2.2.7 on 2020-01-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0027_remove_account_profile_races_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_profile',
            name='account_pic',
            field=models.CharField(default='https://image.flaticon.com/icons/png/512/64/64572.png', max_length=250),
        ),
    ]
