# Generated by Django 2.2.7 on 2020-01-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0028_auto_20200119_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_profile',
            name='transaction_history',
            field=models.TextField(default='|'),
        ),
    ]
